/*
 * This source file was generated by the Gradle 'init' task
 */
package it.unicam.cs.mgc;


import it.unicam.cs.mgc.MicroscopeConfigurator.Controller.HomeController;
import javafx.application.Application;
import javafx.stage.Stage;
import it.unicam.cs.mgc.MicroscopeConfigurator.View.GlobalModel;
import org.apache.jena.rdf.model.Model;

public class App extends Application {

    @Override
    public void start(Stage primaryStage) {
        Model globalModel = GlobalModel.getModelInstance();
        HomeController homeController = new HomeController(primaryStage, globalModel);
        homeController.openHomePage();
    }

    public static void main(String[] args) {
        launch(args);
    }
}